### PR TITLE
changes for building on osx arm64

### PR DESCRIPTION
**Pull request by edoapra**
…nda-forge-pinning 2022.08.31.16.57.19

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changes for building on osx arm64 (a.k.a M1 CPUs)

### CODE REVIEW

**Comment by edoapra** [comment]
The osx arm64 build does not work on the azure x86_64 hardware.

Here is an example from the following log.
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=561149&view=logs&j=385a3385-ae8b-54d1-9abe-3c614f74cb73&t=a5f9d343-149e-5621-6ab9-f0278009be04

```
/bin/sh: /Users/runner/miniforge3/conda-bld/nwchem_1661966075980/work/bin/MACX64/depend.x: Bad CPU type in executable
```
However, I can build on my M1 laptop.

**Comment by ltalirz** [comment]
Apparently, one can request osx arm64 migration by adding the name of the package to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

Not sure whether that automatic migrator will do anything different from what you did; but maybe worth a try?

**Comment by edoapra** [comment]
> Apparently, one can request osx arm64 migration by adding the name of the package to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt
> 
> Not sure whether that automatic migrator will do anything different from what you did; but maybe worth a try?

I have just pushed a couple of changes that should survive the cross-compilation. Let's see what happens.
* arm64 on x86: skip qa tests
* build depend.x with x86 compiler & skip python module

**Comment by edoapra** [comment]
Unfortunately the gfortran  cross-compiler (`arm64-apple-darwin20.0.0-gfortran`) seems to be able to generate objects but the link phase fails to create an executable with the error 
```
ld: library not found for -lgfortran
```

**Pull request closed without merging**
