### PR TITLE
Python 3.10 changes (second try)

### PR DESCRIPTION
**Pull request by edoapra**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Added patch to make NWChem build with Python 3.10 as discussed in https://github.com/conda-forge/nwchem-feedstock/pull/15

### CODE REVIEW

**Comment by edoapra** [comment]
@conda-forge-admin, please rerender

**Comment by edoapra** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
Is there a way to get nwchem to print more information about the test failures?

I notice them in previous builds of the package as well, so we will want to both fix them and make the build fail if they occur.

**Comment by edoapra** [comment]
> Is there a way to get nwchem to print more information about the test failures?
> 
> I notice them in previous builds of the package as well, so we will want to both fix them and make the build fail if they occur.


Commit https://github.com/conda-forge/nwchem-feedstock/pull/18/commits/d9ec0062201a4d0751698366ded193f34d55b31f should address this.

**Comment by ltalirz** [comment]
superseded by https://github.com/conda-forge/nwchem-feedstock/pull/19

**Pull request closed without merging**
