### PR TITLE
add macos build

### LINKED ISSUE #5: MacOS build
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: the current NWChem reciped seems to build only the Linux binary. It should be possible to build a MacOS binary since NWChem does have a MacOS port (`NWCHEM_TARGET=MACX64`) 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : None
       user config file : /Users/edo/.condarc
 populated config files : /Users/edo/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.6.8.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/edo/psi4conda  (writable)
      conda av data dir : /Users/edo/psi4conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/edo/psi4conda/pkgs
                          /Users/edo/.conda/pkgs
       envs directories : /Users/edo/psi4conda/envs
                          /Users/edo/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.6.8 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 1965072434:2016721313
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by ltalirz**
fixes #5

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@edoapra [First OSX build issue](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=318811&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=5888):

```
checking whether Fortran hidden string length convention is after args... 
configure: error: f2c string convention is neither after args nor after string
```

Not sure whether this is related but the default C compiler on the MacOS platform is actually `clang` - I don't know what the `export _CC=gcc` does but perhaps that needs to be adapted?
The fortran compiler is still gfortran, see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=318811&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=176) (also has the default `FFLAGS`)

**Comment by edoapra** [comment]
> @edoapra [First OSX build issue](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=318811&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=5888):
> 
> ```
> checking whether Fortran hidden string length convention is after args... 
> configure: error: f2c string convention is neither after args nor after string
> ```
> 
> Not sure whether this is related but the default C compiler on the MacOS platform is actually `clang` - I don't know what the `export _CC=gcc` does but perhaps that needs to be adapted?
> The fortran compiler is still gfortran, see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=318811&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=176) (also has the default `FFLAGS`)

Clang should work (this is what I routinely use on my laptop). Let me have a look at the logs.

**Comment by edoapra** [comment]
Could you add the following to analyze the failure
```
cat $NWCHEM_TOP/src/tools/build/config.log
```
I think there could be a link problem here, but I need to analyze `$NWCHEM_TOP/src/tools/build/config.log`

**Comment by edoapra** [comment]
The log shows that `NWCHEM_TARGET=LINUX64` was used
Line 248 and later of https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=318811&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=5888

I think the error is at line 24 of https://github.com/ltalirz/nwchem-feedstock/blob/add-macos/recipe/build.sh
It should be changed from
```
if [[ ! -z "$MACOSX_DEPLOYMENT_TARGET" ]]; then
```
to
```
if [[  -z "$MACOSX_DEPLOYMENT_TARGET" ]]; then
```

Created pull requesr
https://github.com/ltalirz/nwchem-feedstock/pull/1

**Comment by ltalirz** [comment]
[It's now using `MACX64`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=318978&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=237) but the error remains the same as above. I'll add `cat $NWCHEM_TOP/src/tools/build/config.log`

**Comment by edoapra** [comment]
The jobs seems to exit after the compilation error and therefore it does not execute the `cat config.log line`

Do we need to hack the compile line to avoid the early exit?
```
make CC=${CC} DEPEND_CC=${CC} _CC=${_CC} FC=${FC} _FC=${_FC} V=1 || true
```
Added pull request
https://github.com/ltalirz/nwchem-feedstock/pull/4

**Comment by ltalirz** [comment]
Thanks @edoapra - yes, that should do the trick (sorry, I could have realized this before).

By the way, just invited you as a collaborator on my fork of the feedstock; feel free to push directly to it

**Comment by edoapra** [comment]
The compiler version for `gfortran` is not correctly detected on MacOS.
https://github.com/conda-forge/nwchem-feedstock/pull/7/commits/e57b4d238d4277b77ac44293af6a944278639c4a is supposed to fix this issue, but it did not seem to work. 
Let's see if we can get good logs this time around.
Unfortunately, conda uses Mavericks  MacOS  and I don't have any reliable way to reproduce these last failures.

**Comment by ltalirz** [comment]
> Let's see if we can get good logs this time around.

I've never had problems with logs from the last commit, but I've noticed before that logs from previous commits can become inaccessible when a new commit is pushed before the previous build finishes.

**Comment by edoapra** [comment]
> > Let's see if we can get good logs this time around.
> 
> I've never had problems with logs from the last commit, but I've noticed before that logs from previous commits can become inaccessible when a new commit is pushed before the previous build finishes.

That's not the problem I have faced with logs. The problem I have found is that there are often lines where I can see only from (let's say) column 10 on. It might be a problem in my browser (javascript) settings

**Comment by ltalirz** [comment]
> Unfortunately, conda uses Mavericks MacOS and I don't have any reliable way to reproduce these last failures.

If that turns out to be a problem, one can bump the minimum MacOS version from 10.9 to a later version, see

https://github.com/conda-forge/cp2k-feedstock/blob/7050a07c7cf6ee40ca2da44402ce0fff128f022f/recipe/conda_build_config.yaml#L8-L11

and 

https://github.com/conda-forge/cp2k-feedstock/blob/7050a07c7cf6ee40ca2da44402ce0fff128f022f/recipe/meta.yaml#L59

> That's not the problem I have faced with logs. The problem I have found is that there are often lines where I can see only from (let's say) column 10 on. It might be a problem in my browser (javascript) settings

I see - I've seen the same but only here with the nwchem logs. There's the "View raw log" button to check whether it's indeed a rendering issue.

**Comment by edoapra** [comment]
> > Unfortunately, conda uses Mavericks MacOS and I don't have any reliable way to reproduce these last failures.
> 
> If that turns out to be a problem, one can bump the minimum MacOS version from 10.9 to a later version, see
> 
> https://github.com/conda-forge/cp2k-feedstock/blob/7050a07c7cf6ee40ca2da44402ce0fff128f022f/recipe/conda_build_config.yaml#L8-L11
> 
> and
> 
> https://github.com/conda-forge/cp2k-feedstock/blob/7050a07c7cf6ee40ca2da44402ce0fff128f022f/recipe/meta.yaml#L59
> 
That seems what we need. Can we go up to 10.15 (at least temporarily for this debugging phase)?
> > That's not the problem I have faced with logs. The problem I have found is that there are often lines where I can see only from (let's say) column 10 on. It might be a problem in my browser (javascript) settings
> 
> I see - I've seen the same but only here with the nwchem logs. There's the "View raw log" button to check whether it's indeed a rendering issue.

Unfortunately, "View raw log" works only after the step has completed and the last time the jobs were running for more than one hour (or maybe two).

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by edoapra** [comment]
Found the root cause of the MacOS failures
https://github.com/conda-forge/gfortran_osx-64-feedstock/issues/11#issuecomment-576256336

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
rerendering is necessary here in order for the builds to actually take into account the change in osx version (so far version 10.15 was still used)

**Comment by ltalirz** [comment]
thanks a lot for your work on this!
fingers crossed that this last build passes - if yes, we have the osx build

**Comment by ltalirz** [comment]
Tests on OSX [seem to pass fine](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=319456&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445&l=72732)

there are a couple of [`is not an elf` errors during packaging](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=319456&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445&l=48242) but since the tests passed I am assuming these are not critical (?). Will open an issue for this to keep track.

**Pull request merged**
