### PR TITLE
Python 3.10 changes and re-rendered

### PR DESCRIPTION
**Pull request by edoapra**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Same as previous pull request  https://github.com/conda-forge/nwchem-feedstock/pull/18, plus  rerendering commit https://github.com/conda-forge/nwchem-feedstock/commit/48d310288b259d494f623b8cea85b504cf98567e  

Summary of changes  
* patch to make NWChem build with Python 3.10 as discussed in https://github.com/conda-forge/nwchem-feedstock/pull/15. 
* fixed error in running QA tests
* added patch for osx arm64

### CODE REVIEW

**Comment by ltalirz** [comment]
Thanks for the update @edoapra ! 

the only one small suggestion I might still have (unless you've already fixed it) would be to adapt the test script so that it will exit with a non-zero exit code, if any of the tests fails (on the current `main` that did not  seem to have been the case). 
I guess one just needs to adapt the phrase that is grepped

https://github.com/conda-forge/nwchem-feedstock/blob/b3e881242bc2d68f87881a4b6ff5e40b355f7610/recipe/run_test.sh#L22-L24

**Comment by edoapra** [comment]
> Thanks for the update @edoapra !
> 
> the only one small suggestion I might still have (unless you've already fixed it) would be to adapt the test script so that it will exit with a non-zero exit code, if any of the tests fails (on the current `main` that did not seem to have been the case). I guess one just needs to adapt the phrase that is grepped
> 
> https://github.com/conda-forge/nwchem-feedstock/blob/b3e881242bc2d68f87881a4b6ff5e40b355f7610/recipe/run_test.sh#L22-L24

Commit https://github.com/conda-forge/nwchem-feedstock/pull/19/commits/6f4b1bead224f92a13c90634a7507a926af8ffef addresses this issue in the test script.

I would like to push a change to build osx arm64 (aka M1). Is this change OK for correctly triggering the re-rendering process?
```
--- conda-forge.yml	2022-08-29 14:59:00.000000000 -0700
+++ conda-forge.yml.arm64	2022-08-31 09:46:35.000000000 -0700
@@ -2,3 +2,6 @@
 github:
   branch_name: main
   tooling_branch_name: main
+build_platform:
+  osx_arm64: osx_64
+test: native_and_emulated
```

**Comment by ltalirz** [comment]
Thanks for the fix @edoapra !
I just realized that you are not yet listed as a maintainer of this repository - if you would like me to add you, just let me know and you will be able to merge the PR yourself next time.

As for your question, it looks like you already know more than me...
as far as I'm aware, a pull request to add support for the ARM platform should be triggered automatically as soon as all of the dependencies of the feedstock have ARM builds (this already happened on a couple of my other feedstocks). However, I have no experience in triggering it myself

**Comment by edoapra** [comment]
> Thanks for the fix @edoapra ! I just realized that you are not yet listed as a maintainer of this repository - if you would like me to add you, just let me know and you will be able to merge the PR yourself next time.

Sure.

**Pull request merged**
